/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'serviceType' : string,
  'name' : string,
  'email' : string,
  'suburb' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface QuoteRequest {
  'bedrooms' : bigint,
  'name' : string,
  'email' : string,
  'suburb' : string,
  'timestamp' : Time,
  'phone' : string,
  'bathrooms' : bigint,
  'extras' : Array<string>,
  'carpetCleaning' : boolean,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllQuoteRequests' : ActorMethod<[], Array<QuoteRequest>>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'submitQuoteRequest' : ActorMethod<
    [string, string, string, string, bigint, bigint, boolean, Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];